### ISSUE TITLE
Suggestion: Packaging compiled classes in a .jar using a -j/-jar parameter

### ISSUE THREAD

**Issue by 0x0verflow** [trueFireblade/BetterJavaCompile#1]
As an example the syntax could look like this:
```bjc -j```

Or with a specific output location:
```bjc -jar big-fat-jar.jar```

You could accomplish this using Java's ``jar`` command to package all compiled class-files to a .jar

**Comment by trueFireblade** [comment]
I added that feature but with other syntax, look at the manpage for more details!
